spring:
  application:
    name: server-config
  cloud:
    config:
      label: master    #配置仓库的分支
      server:
        git:
          uri: https://github.com/forezp/SpringcloudConfig/   #仓库地址
          username: bian1234                                  #用户名
          password: biangit123                                #密码
          search-paths: respo                                 #仓库路径
server:
  port: 8120

#spring.cloud.config.server.git.uri：配置git仓库地址
#spring.cloud.config.server.git.searchPaths：配置仓库路径
#spring.cloud.config.label：配置仓库的分支
#spring.cloud.config.server.git.username：访问git仓库的用户名
#spring.cloud.config.server.git.password：访问git仓库的用户密码