eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 8110
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /ribbon/**
      serviceId: service-ribbon     #以api-a开头的请求都转发到ribbon服务商上
    api-b:
      path: /feign/**
      serviceId: service-feign    #以api-b开头的请求都转发到feign服务商上
hystrix:                          #断路器配置
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000